Repository Mirasaki/dayz-leaderboard-nextjs, pull requests merged in 2023-01, with the labels that each got.

#6 Fix title abnormal word-break
  src/styles/Home.module.css
Labels: bug

#7 feat: blacklist for admins
  README.md
  config.example.json
  src/pages/index.jsx
Labels: enhancement

#11 feat: hide player statistics for blacklisted members
  README.md
  config.example.json
  package.json
  src/pages/index.jsx
Labels: enhancement

#12 Changes to the Blacklist
  README.md
  src/pages/index.jsx
Labels: invalid

#14 feat: background image config
  README.md
  config.example.json
  public/icon.png
  src/components/BackgroundImage.jsx
Labels: documentation, enhancement

#15 feat: configurable sort values, including default sorting
  README.md
  config.example.json
  public/logo.png
  src/pages/index.jsx
Labels: documentation, enhancement
